controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - front_left_wheel_joint
        - front_right_wheel_joint
        - back_left_wheel_joint
        - back_right_wheel_joint
    skid_steer_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint"]
      right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]
      wheel_separation: 0.5
      wheel_radius: 0.15
      publish_rate: 50
