# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Hz
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
#       joints:
#         - joint_left_wheel
#         - joint_right_wheel
#     skid_steer_controller:
#       type: diff_drive_controller/DiffDriveController
#       left_wheel_names: ["joint_left_wheel"]
#       right_wheel_names: ["joint_right_wheel"]
#       wheel_separation: 0.322
#       wheel_radius: 0.195
#       publish_rate: 50

controller_manager:
  ros__parameters:
    update_rate: 100

    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # joint_state_controller:
    #   type: joint_state_controller/JointStateController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


# joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - 'joint_left_wheel'
#       - 'joint_right_wheel'
#     command_interfaces:
#       - velocity
#     state_interfaces:
#       - velocity


diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["joint_left_wheel"]
    right_wheel_names: ["joint_right_wheel"]
    wheel_separation: 0.322
    wheel_radius: 0.195
    publish_rate: 50.0
    odom_frame_id: /base_link
    enale_odom_tf: false