
robot1:
  controller_manager:
    ros__parameters:
      update_rate: 100


      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController


  diff_drive_controller:
    ros__parameters:
      left_wheel_names: ["joint_left_wheel"]
      right_wheel_names: ["joint_right_wheel"]
      wheel_separation: 0.322 
      wheel_radius: 0.195
      publish_rate: 50.0
      odom_frame_id: /odom
      # odom_frame_id: /base_link
      base_frame_id: /base_link
      enale_odom_tf: false
      

robot2:
  controller_manager:
    ros__parameters:
      update_rate: 100

 

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController




  diff_drive_controller:
    ros__parameters:
      left_wheel_names: ["joint_left_wheel"]
      right_wheel_names: ["joint_right_wheel"]
      wheel_separation: 0.322
      wheel_radius: 0.195
      publish_rate: 50.0
      odom_frame_id: /odom
      # odom_frame_id: /base_link
      base_frame_id: /base_link
      enale_odom_tf: false
      